runtime: python310
entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  CONVERTAPI_SECRET: "UMWYdoGAZ5VxE1zk7BPqtwCyYHQq2yrs"

handlers:
  - url: /static
    static_dir: static
